version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
